# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["pedljm"] %>
  email_provider_password: <%= ENV["Camwithd3v"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["pedljm"] %>
  mailchimp_list_id: <%= ENV['2JOONGMIn!'] %>
  owner_email: <%= ENV["pedljm@outlook.com"] %>
  secret_key_base: very_long_random_string

test:
  secret_key_base: very_long_random_string

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["pedljm"] %>
  email_provider_password: <%= ENV["Camwithd3v"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["bf0f6f0a9699d33a1c55a33f304c43ee-us14"] %>
  mailchimp_list_id: <%= ENV["36f86d76b6"] %>
  owner_email: <%= ENV["pedljm@outlook.com"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
